# Change these first
owner: expandana # Your GitHub username
repo: expandana-status # Your GitHub repository name

# Add your sites here
sites:
    - name: Production - Learn
    url: https://learn.expandana.id
    - name: Production - Xena
    url: https://xena.expandana.id
    - name: Development - API Gateway
    url: https://api-svc-development.expandana.id/v1/status

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.expandana.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://learn.expandana.id/expandana-text-logo-blue.png
  name: Expandana Status
  introTitle: "**Services Status Dashboard**"
  introMessage: This is a dashboard to monitoring services uptime
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://learn.expandana.id

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
